### ISSUE TITLE
Pybonjour Issue. No distributions found for Pybonjour. (my solution included) 

### ISSUE THREAD

**Issue by shivang1989** [hauckwill/linconnect-server#88]
While running the installations script for LinConnect on Ubuntu 14.04LTS, I faced this issue stating _"Could not find any downloads that satisfy the requirement pybonjour"_

I think the repo for Pybonjour is gone and the script was not able to find it.

Solved it by explicitly installing pybonjour. 

`pip install -e git+https://github.com/Eichhoernchen/pybonjour.git#egg=pybonjour` 

P.S - I was not able to run LinConnect on Ubuntu 14.04 successfully. It just showed test notifications. It even showed notifications related to enabling of apps present inside my Android device but no success after that. 

Example - I enabled "Phone" as I only need to see call notifications. While I ticked the "Phone" app, the notification stating "Call notification enabled" was displayed on Ubuntu desktop but while tried calling to my android device, I din't get any notification.

**Comment by 3ruce** [comment]
Perfect, thank you - worked for me...

**Comment by alge77** [comment]
That works with Ubuntu 16.04 also. Thanks for sharing.

**Comment by ByScripts** [comment]
Your solution to launch server is working. But the app doesn't work for me neither.

As you said, I get the first notification to say it's activated, be when I receive a call, a message, a mail or any other notification, I don't get it on Ubuntu, although all apps are checked in config.

**Comment by ktpx** [comment]
@ByScripts What version of android? (I'm having same issue..must be app problem)

**Comment by mandasou** [comment]
@shivang1989 

Getting this while trying to run 'pip install -e git+https://github.com/Eichhoernchen/pybonjour.git#egg=pybonjour'


"Could not import setuptools which is required to install from a source distribution.
Please install setuptools."

**Comment by ArkJzzz** [comment]
arkjzzz@laptop:~$ sudo -H pip install -e git+https://github.com/Eichhoernchen/pybonjour.git#egg=pybonjour
Obtaining pybonjour from git+https://github.com/Eichhoernchen/pybonjour.git#egg=pybonjour
  Updating ./src/pybonjour clone
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/arkjzzz/src/pybonjour/setup.py", line 32, in <module>
        import pybonjour
      File "/home/arkjzzz/src/pybonjour/pybonjour.py", line 824, in <module>
        _create_function_bindings()
      File "/home/arkjzzz/src/pybonjour/pybonjour.py", line 807, in _create_function_bindings
        for name, (restype, errcheck, outparam, argtypes) in specs.iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/arkjzzz/src/pybonjour/
