### ISSUE TITLE
Arch Linux Install and Setup Errors

### ISSUE THREAD

**Issue by godlikemouse** [hauckwill/linconnect-server#90]
This is what I'm seeing when running the install.sh on Arch Linux.

$ sudo ./install.sh 
Install LinConnect server? [Y/N]y
Install dependencies automatically (for Debian-based distros) [Y/N]n
Install dependencies automatically (for Fedora distros) [Y/N]nInstall dependencies automatically (for Arch distros) [Y/N]yInstalling dependencies
warning: python2-2.7.12-1 is up to date -- reinstalling
warning: python2-pip-8.1.2-1 is up to date -- reinstalling
warning: python2-gobject-3.20.1-1 is up to date -- reinstalling
warning: avahi-0.6.32-2 is up to date -- reinstalling
warning: git-2.10.0-1 is up to date -- reinstalling
warning: python2-pybonjour-1.1.1-4 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (6) avahi-0.6.32-2  git-2.10.0-1  python2-2.7.12-1  python2-gobject-3.20.1-1
             python2-pip-8.1.2-1  python2-pybonjour-1.1.1-4

Total Installed Size:  109.49 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] y
(6/6) checking keys in keyring                          [##############################] 100%
(6/6) checking package integrity                        [##############################] 100%
(6/6) loading package files                             [##############################] 100%
(6/6) checking for file conflicts                       [##############################] 100%
(6/6) checking available disk space                     [##############################] 100%
:: Processing package changes...
(1/6) reinstalling python2                              [##############################] 100%
(2/6) reinstalling python2-pip                          [##############################] 100%
(3/6) reinstalling python2-gobject                      [##############################] 100%
(4/6) reinstalling avahi                                [##############################] 100%
(5/6) reinstalling git                                  [##############################] 100%
(6/6) reinstalling python2-pybonjour                    [##############################] 100%
:: Running post-transaction hooks...
(1/1) Updating the desktop file MIME type cache...
Install Python dependencies
Requirement already satisfied (use --upgrade to upgrade): cherrypy in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from cherrypy)
Press any key to continue...
Installing LinConnect...
Setting up LinConnect...
Autostart LinConnect server on boot? [Y/N]n
Install complete. Start LinConnect server now? [Y/N]y
Fetching origin
Fetching upstream
From https://github.com/hauckwill/linconnect-server
 * [new branch]      master     -> upstream/master
HEAD is now at 3a86225 Merge pull request #80 from pecey/master
linconnect_server.py:39: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Creating conf.ini
Configuration instructions at http://localhost:9090
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "linconnect_server.py", line 168, in initialize_bonjour
    callBack=register_callback)
  File "/usr/lib/python2.7/site-packages/pybonjour.py", line 1132, in DNSServiceRegister
    None)
  File "/usr/lib/python2.7/site-packages/pybonjour.py", line 286, in _errcheck
    raise cls(result)
BonjourError: (-65537, 'unknown')

Traceback (most recent call last):
  File "linconnect_server.py", line 203, in <module>
    notif.show()
GLib.Error: g-spawn-exit-error-quark: Error spawning command line 'dbus-launch --autolaunch=30d4723c1c4c4a238efa42ee1cb6640b --binary-syntax --close-stderr': Child process exited with code 1 (1)

**Comment by clockworkgeek** [comment]
I just tried on Arch with [the AUR version](https://aur.archlinux.org/packages/linconnect-server-git/) and it worked first time.

**Comment by rdmartins** [comment]
The AUR version doesn't install two python dependencies.
Install it with `# pip2 install cheroot portend` or `$ pip2 install cheroot portend --user`.

The python Cheroot module can be installed via pacman (the recommended method).

**Comment by tsaber** [comment]
```
/usr/lib/linconnect-server/linconnect_server.py:39: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Loading conf.ini
Configuration instructions at http://localhost:9090
Traceback (most recent call last):
  File "/usr/lib/linconnect-server/linconnect_server.py", line 203, in <module>
    notif.show()
gi.repository.GLib.Error: g-io-error-quark: Address element “/run/user/1000/dbus/user_bus_socket” does not contain a colon (:) (13)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/linconnect-server/linconnect_server.py", line 169, in initialize_bonjour
    signal.signal(signal.SIGTERM, sigterm_handler)
ValueError: signal only works in main thread
```

same almost here. I have both modules installed
